# Generated by Django 2.2.1 on 2019-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Quotes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('author_name', models.CharField(max_length=50, verbose_name='Who added?')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved')], default='new', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
